### ISSUE TITLE
Cache Problem in files listing

### ISSUE THREAD

**Issue by MohsinQK** [fnagel/pluploadfe#12] opened 2017-10-06 15:13 UTC
If a upload new Files to the directory they would not show until I remove the cache from the backend.

**Comment by fnagel** [comment] 2018-08-07 07:48
Sorry for the late response. Seems I've missed this issue. 

Any news on this? Still an issue?

**Comment by MohsinQK** [comment] 2018-08-07 07:50
I have not tested that, it's like almost a year ago :)

**Comment by fnagel** [comment] 2018-08-07 07:52
Thanks for the fast answer. I will close this for now as I'm not able to reproduce. Please reopen if needed!

**Closed as completed by fnagel** 2018-08-07 07:52 UTC
Labels: bug
