### ISSUE TITLE
Seems not to work with FLUID or BootstrapPackage

### ISSUE THREAD

**Issue by Moongazer** [fnagel/pluploadfe#15] opened 2019-12-06 13:15 UTC
I installed the extension, placed the plugin (disabled FEuser in config), but the Plugin is not rendered, but all CSS and JS files are included.

Could it be because the BootstrapPackage wraps all CEs with custom FLUID templates? The header of the plugin is rendered, but no content from the `template.html`.

Another thing what jumped into my eyes is in the TS Object Browser, all other working extensions using the USER setting, but for this extension is says `[pluploadfe_pi1] = < plugin.tx_pluploadfe_pi1`. I tried to manually changed it to USER with userFunc, vendorName, and pluginName etc... but than only exceptions are thrown.

![t3-pluploadfe](https://user-images.githubusercontent.com/1685510/70325605-aaba7800-1832-11ea-888b-ccb05620b8dd.png)

Is there something else what I can try? In the extension repro it says that it should run with TYPO3 v9.

System:
PHP 7.3
TYPO3 9.5.8
PluploadFE Extension 3.0.0
BootstrapPackage Extension 11.0.0

**Comment by fnagel** [comment] 2019-12-06 21:07
First of all: thanks for the great bug report. It's always nice to have all info right from the  beginning!

I'm testing my extensions in a fresh introduction package (EXT:introduction which is using EXT:bootstrap_package) instance. My current setup is a PHP 7.2 (this should be no issue IMO) with TYPO3 9.5.11 and EXT:bootstrap_package 10.0.8 together with EXT:fluid_styled_content.


So, your setup should work and we need to figure out why that's not the case. 


The extensions TS looks somewhat different as all other as its still a PiBase plugin and not an extbase one. Please check how your plugin TS looks like, this it how it looks in my instance:
![grafik](https://user-images.githubusercontent.com/116824/70356270-4ae4c100-1874-11ea-94f3-ceff959d7dea.png)


> disabled FEuser in config

So like this, right?
![grafik](https://user-images.githubusercontent.com/116824/70356013-baa67c00-1873-11ea-94c8-9fc2d0585069.png)

Would you mind updating your TYPO3 instance, just to be sure?

**Comment by fnagel** [comment] 2019-12-06 21:16
I tried to update my EXT:bk2k/bootstrap-package to 11 as well but that's not that easy due to EXT:introduction package dependency constraints. Are you able to downgrade, to eliminate the option the issue is caused by that?

**Comment by Moongazer** [comment] 2019-12-07 11:29
> Would you mind updating your TYPO3 instance, just to be sure?

Oh well - the update to v9.5.11 was the solution! It's a bit odd as its just a tiny minor version difference, but who knows what they changed in the core^^ I guess its not worth to debug this behaviour further, as long as it not happens again in a future version right?

Anyway, thanks a lot for your feedback, I highly appreciate your work :-)

PS: If you do want to debug this, you can let me know if you have any idea what I can try or test for you (its only a symlink change for me to downgrade to the affected version again)

**Comment by fnagel** [comment] 2019-12-08 12:30
Ahh good to hear it works now! Sadly I don't now exactly with which version of 9.5 I've started testing but as its now documented here, I'm not really into investing time here to fix it. 

We'll see if it occurs again with upcoming version but I don't think so.

**Comment by phil64** [comment] 2020-01-02 10:25
Hi,
Faced with the same problem (TYPO3 9.5.13, pluploadfe 4.0.0)
After investigations, i managed to make it works by moving this part of code from ext_tables.php to ext_localconf.php:
```

    // Add plugin
    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScript(
        'FelixNagel.Pluploadfe',
        'setup',
        'plugin.tx_pluploadfe_pi1.userFunc = FelixNagel\Pluploadfe\Controller\Pi1Controller->main'
        );
```

**Comment by fnagel** [comment] 2020-01-02 15:03
@phil64 Thanks for the hint! Seems you're right, even the method description mentions this should be placed in `ext_localconf.php` files. I've pushed a proposed fix. Would you mind testing this and give feedback?

Might be related to #13

**Comment by phil64** [comment] 2020-01-03 07:48
Hi,
It's exactly what i did, and it works.

**Comment by fnagel** [comment] 2020-01-03 08:48
Very nice. I will push a hotfix release today. Thanks for your contribution!

**Closed as completed by fnagel** 2020-01-03 08:48 UTC
Labels: bug
