### ISSUE TITLE
Plugin disappears

### ISSUE THREAD

**Issue by keelMi** [fnagel/pluploadfe#13] opened 2019-02-18 08:43 UTC
The Plugin disappears in FE every few days. Everytime we must exclude it from Static Template and then include it again. on TYPO3 8.7

**Comment by fiedomedia** [comment] 2019-02-28 07:47
@keelMi I had a similar problem with TYPO 8.7.

I've fixed that by inserting the plupload plugin on my own in TypoScript with
```
lib.pluploadfe = USER
lib.pluploadfe {
    userFunc = FelixNagel\Pluploadfe\Controller\Pi1Controller->main
    templateFile = EXT:myExtension/path/to/template.html
    uid = my-custom-identifier
    configUid = 1
}
```

Note that adding the userFunc is important here.

**Comment by fnagel** [comment] 2019-03-12 17:54
@keelMi @fiedomedia 

What version of TYPO3 and this extension are you using? 
Does this happen on a specific instance only? 
"Every few days" is hard to debug. Any more info on how to reproduce this?
What does "disappear" mean? That there is no more rendering in FE? Or is it even gone in the BE page module?
Is the extension TS included on root or using an additional template?

**Comment by ajikmi** [comment] 2019-06-04 10:00
we are using 2.1.0. It is happening on every instance. No more rendering in FE.
We include it in Root TS.

**Comment by fnagel** [comment] 2019-07-11 14:08
I'm not able to reproduce this. Any help is appreciated!

**Comment by fnagel** [comment] 2020-01-02 15:04
Pushed a bugfix which might fix this issue. Please try latest master commit (449165c1ec39e0b5a0196a93d0d99da9266ee742)!

**Comment by fnagel** [comment] 2020-01-03 13:56
Proposed fix is included in the 4.0.1 release.

**Comment by fnagel** [comment] 2020-10-09 15:08
Any feedback on this issue?

**Comment by fnagel** [comment] 2021-03-15 15:57
Closed as no feedback was given. Please reopen or create a new ticket if needed.

**Closed as completed by fnagel** 2021-03-15 15:57 UTC
Labels: bug, help wanted
